Update bookdown
r4ds/bookclub-dsieur pull request #38
Opened 2021-04-11 18:09 UTC by ivelasq

Thanks!

2021-04-12 13:00 UTC, tanho63 commented on 01-retitle.Rmd
> +`r knitr::include_url("https://www.youtube.com/watch?v=6k_F6XGEmqs")`
Don't forget that you need the embed link for these to work correctly!

2021-04-12 13:00 UTC, tanho63 commented on 01-retitle.Rmd
> +`r knitr::include_url("https://www.youtube.com/watch?v=6k_F6XGEmqs")`
also embed

2021-04-12 13:01 UTC, tanho63 requested changes
I `think` we talked about the embed link thing from last time but if not, let me know and I can help you find them!

2021-04-12 13:29 UTC, ivelasq commented
Ah, thanks! I think I fixed them all...

2021-04-12 13:45 UTC, tanho63 commented
@ivelasq can you also hit the very first one at line 19 while you're on this? :)

2021-04-12 13:50 UTC, ivelasq commented
Nice catch! Thanks.

2021-04-12 14:35 UTC, tanho63 commented
Working through some GHA issues (unrelated to this PR)

-
Tan Ho
________________________________
From: Isabella Velásquez ***@***.***>
Sent: Monday, April 12, 2021 9:50:33 AM
To: r4ds/bookclub-dsieur ***@***.***>
Cc: Tan Ho ***@***.***>; Comment ***@***.***>
Subject: Re: [r4ds/bookclub-dsieur] Update bookdown (#38)


Nice catch! Thanks.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/r4ds/bookclub-dsieur/pull/38#issuecomment-817828734>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJCRZ37GWN52PF5BZUU7RDTTIL3CTANCNFSM42X5KUMQ>.

2021-04-16 21:56 UTC, tanho63 approved these changes

2021-04-16 21:57 UTC, merged